import Head from "next/head";
import styles from "./index.module.scss";
import Layout from "../components/Layout/layout";
import FilterButton from "../components/FilterButton";
import VerticalCard from "../components/HomeCards/vertical";
import HomeProducts from "../components/Product/HomeProducts";
import HorizontalCard from "../components/HomeCards/horizontal";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Panaderia La Toscana</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.header}>
            <h1 className={styles.title}>
              <span className={styles.emoji}>🎂</span>Productos
            </h1>
            <div className={styles.headerButtons}>
              <FilterButton type="sort" style={{ marginRight: 20 }} />
              <FilterButton count={0} />
            </div>
          </div>
          <HomeProducts>
            <HorizontalCard
              bgColor="#F6BD60"
              title="LA TOSCANA"
              image="https://i.ibb.co/wL3nWkm/Pngtree-memphis-style-line-point-line-3797599.png"
            />
            <HorizontalCard
              bgColor="#dec8f3"
              title="Visitanos"
              image="/cupcake-1.png"
              desc="11 Avenida S, San Pedro Sula 21104, Honduras"
            />
            <VerticalCard bgColor="#F9D79F" />
            <VerticalCard bgColor="#F9D79F" />
          </HomeProducts>
          <HomeProducts reverse>
            <HorizontalCard
              bgColor="#F3C1B9"
              title="LA TOSCANA"
              image="https://i.ibb.co/wL3nWkm/Pngtree-memphis-style-line-point-line-3797599.png"
            />
            <HorizontalCard
              bgColor="#E94135"
              title="Visitanos"
              image="Fleur.svg.png"
              desc="11 Avenida S, San Pedro Sula 21104, Honduras"
            />
            <VerticalCard bgColor="#F0857F" />
            <VerticalCard bgColor="#F0857F" />
          </HomeProducts>
          <HomeProducts>
            <HorizontalCard
              bgColor="#99E6B0"
              title="LA TOSCANA"
              image="https://i.ibb.co/wL3nWkm/Pngtree-memphis-style-line-point-line-3797599.png"
            />
            <HorizontalCard
              bgColor="#f3e6c8"
              title="Visitanos"
              desc="11 Avenida S, San Pedro Sula 21104, Honduras"
            />
            <VerticalCard bgColor="#D1E69A" />
            <VerticalCard bgColor="#D1E69A" />
          </HomeProducts>
        </main>
      </div>
    </Layout>
  );
}
